### ISSUE TITLE
Adaptation to correctly calculate in case of variance heterogeneity

### ISSUE THREAD

**Issue by JoFAM** [openanalytics/BIGL#1]
We forked the repo to implement a few changes that give more correct results in case of variance heterogeneity. This is a project carried out by Annelies Tourny under supervision of Olivier Thas.

The fork is located here: https://github.com/CenterForStatistics-UGent/BIGL

When adaptations are done, we'll issue a pull request to get the changes updated on CRAN. In case of questions, mail Joris.Meys@UGent.be or Annelies.Tourny@UGent.be

**Comment by mnazarov** [comment]
This is now merged into 'master'
