### ISSUE TITLE
formal argument "xlab" matched by multiple actual arguments

### ISSUE THREAD

**Issue by jaandrel** [openanalytics/BIGL#3]
Hi,

I'm trying to run a contour plot with my own x and y labels.  An example of the code I'm using is below and worked previously, but now gives me the following error. 

contour(maxR_B, main = paste0("Cell line contour plot for maxR"),  scientific = FALSE, cutoff = cutoff,
        xlab = "Dose (Drug1)", 
        ylab = "Dose (Drug2)")

_Error in plot.maxR(x$maxR, xlab = xlab, ylab = ylab, ...) : 
  formal argument "xlab" matched by multiple actual arguments_

The documentation suggests this should still be possible and it would be really helpful to get this functionality back, simple as it is.  Any suggestions?

**Comment by mnazarov** [comment]
Thanks for reporting, this has been now fixed.

**Comment by jaandrel** [comment]
Brilliant! thanks so much.
