### ISSUE TITLE
plotting with rglwidget -- no 3D plot 

### ISSUE THREAD

**Issue by sarahalmar** [openanalytics/BIGL#6]
I have tried to plot with the rglwidget by running the vignette source code but only a black box appears. I have tried to produce a 3D plot using the rgl iris vignette data and I was able to using plot_3D, however since the code here is not a dataframe, I cannot use that. I am not sure why only a black box appears in the viewer. 

Any help is appreciated. I run my R code through a Domino workspace with R 3.6. 

Thanks. 
<img width="1263" alt="Screen Shot 2021-03-02 at 8 32 34 PM" src="https://user-images.githubusercontent.com/79660534/109749669-1b248600-7ba9-11eb-949b-c02ba2247464.png">

**Comment by dmurdoch** [comment]
This appears to be an rgl bug, not a BIGL bug.  See https://github.com/dmurdoch/rgl/issues/40
